// Generated by scripts/optimize-advertorial-media.mjs from the original site assets.
export const media = {
  "cad_design": {
    "width": 1376,
    "height": 768,
    "src": "/advertorial/media/cad_design.160ac62dc67d.1376.webp",
    "srcSet": "/advertorial/media/cad_design.ca438b053f1a.480.webp 480w, /advertorial/media/cad_design.7a54a6c0267d.768.webp 768w, /advertorial/media/cad_design.160ac62dc67d.1376.webp 1376w",
    "variants": [
      {
        "width": 480,
        "src": "/advertorial/media/cad_design.ca438b053f1a.480.webp",
        "bytes": 10296
      },
      {
        "width": 768,
        "src": "/advertorial/media/cad_design.7a54a6c0267d.768.webp",
        "bytes": 20846
      },
      {
        "width": 1376,
        "src": "/advertorial/media/cad_design.160ac62dc67d.1376.webp",
        "bytes": 49558
      }
    ]
  },
  "gold_pour": {
    "width": 1448,
    "height": 1086,
    "src": "/advertorial/media/gold_pour.a1e6d2b63f80.1448.webp",
    "srcSet": "/advertorial/media/gold_pour.1d6237eb4c75.480.webp 480w, /advertorial/media/gold_pour.c1b193cf1a08.768.webp 768w, /advertorial/media/gold_pour.a1e6d2b63f80.1448.webp 1448w",
    "variants": [
      {
        "width": 480,
        "src": "/advertorial/media/gold_pour.1d6237eb4c75.480.webp",
        "bytes": 14014
      },
      {
        "width": 768,
        "src": "/advertorial/media/gold_pour.c1b193cf1a08.768.webp",
        "bytes": 31066
      },
      {
        "width": 1448,
        "src": "/advertorial/media/gold_pour.a1e6d2b63f80.1448.webp",
        "bytes": 88502
      }
    ]
  },
  "hand_setting": {
    "width": 1122,
    "height": 1402,
    "src": "/advertorial/media/hand_setting.5f43f420b018.1122.webp",
    "srcSet": "/advertorial/media/hand_setting.039a87ac16d2.192.webp 192w, /advertorial/media/hand_setting.55a2ed5d6f37.384.webp 384w, /advertorial/media/hand_setting.53659b5ce24c.640.webp 640w, /advertorial/media/hand_setting.5f43f420b018.1122.webp 1122w",
    "variants": [
      {
        "width": 192,
        "src": "/advertorial/media/hand_setting.039a87ac16d2.192.webp",
        "bytes": 3422
      },
      {
        "width": 384,
        "src": "/advertorial/media/hand_setting.55a2ed5d6f37.384.webp",
        "bytes": 7550
      },
      {
        "width": 640,
        "src": "/advertorial/media/hand_setting.53659b5ce24c.640.webp",
        "bytes": 13770
      },
      {
        "width": 1122,
        "src": "/advertorial/media/hand_setting.5f43f420b018.1122.webp",
        "bytes": 28638
      }
    ]
  },
  "editorial_bands": {
    "width": 1448,
    "height": 1086,
    "src": "/advertorial/media/editorial_bands.3655aa01df9d.1448.webp",
    "srcSet": "/advertorial/media/editorial_bands.f517b7c6b91c.192.webp 192w, /advertorial/media/editorial_bands.54299f00a684.384.webp 384w, /advertorial/media/editorial_bands.8305c5fe1998.640.webp 640w, /advertorial/media/editorial_bands.3655aa01df9d.1448.webp 1448w",
    "variants": [
      {
        "width": 192,
        "src": "/advertorial/media/editorial_bands.f517b7c6b91c.192.webp",
        "bytes": 2864
      },
      {
        "width": 384,
        "src": "/advertorial/media/editorial_bands.54299f00a684.384.webp",
        "bytes": 6846
      },
      {
        "width": 640,
        "src": "/advertorial/media/editorial_bands.8305c5fe1998.640.webp",
        "bytes": 12848
      },
      {
        "width": 1448,
        "src": "/advertorial/media/editorial_bands.3655aa01df9d.1448.webp",
        "bytes": 41118
      }
    ]
  },
  "fancy_yellow": {
    "width": 1448,
    "height": 1086,
    "src": "/advertorial/media/fancy_yellow.b49f5274d1f1.1448.webp",
    "srcSet": "/advertorial/media/fancy_yellow.dad184db626f.192.webp 192w, /advertorial/media/fancy_yellow.6f54602fcff3.384.webp 384w, /advertorial/media/fancy_yellow.31c7c2cf96d9.640.webp 640w, /advertorial/media/fancy_yellow.b49f5274d1f1.1448.webp 1448w",
    "variants": [
      {
        "width": 192,
        "src": "/advertorial/media/fancy_yellow.dad184db626f.192.webp",
        "bytes": 1942
      },
      {
        "width": 384,
        "src": "/advertorial/media/fancy_yellow.6f54602fcff3.384.webp",
        "bytes": 5036
      },
      {
        "width": 640,
        "src": "/advertorial/media/fancy_yellow.31c7c2cf96d9.640.webp",
        "bytes": 11020
      },
      {
        "width": 1448,
        "src": "/advertorial/media/fancy_yellow.b49f5274d1f1.1448.webp",
        "bytes": 40784
      }
    ]
  }
} as const;
